apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    lang: java
    type: config
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: tdoddareddy/kube-eurekaserver:0.0.2-SNAPHOST
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver-service
  labels:
    app: eurekaserver
spec:
  type: ClusterIP
  selector:
    app: eurekaserver
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
