apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-client-scs-deployment
  labels:
    lang: java
    type: frontend
    app: sb-client-scs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sb-client-scs
  template:
    metadata:
      labels:
        app: sb-client-scs
    spec:
      containers:
        - name: sb-client
          image: tdoddareddy/kube-sbservice-client-scs:0.0.4-SNAPSHOT
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sb-client-scs
  labels:
    app: sb-client-scs
spec:
  type: LoadBalancer
  selector:
    app: sb-client-scs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
