apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-service
  labels:
    app: sb-service
data:
  application-dev.yaml: |-
    greetingLanguage: French

  application-kubernetes.yaml: |-
    greetingLanguage: Spanish

  application.yaml: |-
    management:
      endpoints:
        web:
          exposure:
            include: "*"

    spring:
      application:
        name: sb-service
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate:
          ddl-auto: update
      cloud:
        kubernetes:
          config:
            name: sb-service
            namespace: default
          secrets:
            name: sb-service
            namespace: default
            enabled: true
            paths: /app/secrets
            enableApi: true

    logging:
      level:
        org:
          springframework: DEBUG
---
apiVersion: v1
kind: Secret
metadata:
  name: sb-service
data:
  url: amRiYzpteXNxbDovL215c3FsLXNpbmdsZS1ub2RlLXJlbGVhc2U6MzMwNi9ncmVldGluZ2RiCg== #jdbc:mysql://mysql-single-node-release:3306/greetingdb
  username: cm9vdAo= #root
  password: ZFNJTllWTmNRNwo= #dSINYVNcQ7

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-service-deployment
  labels:
    lang: java
    type: config
    app: sb-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-service
  template:
    metadata:
      labels:
        app: sb-service
    spec:
      containers:
        - name: sb-service
          image: tdoddareddy/kube-sbservice:0.0.9-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: sb-service
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sb-service
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sb-service
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /app/resources
            - name: secret-volume
              mountPath: /app/secrets
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: sb-service
        - name: secret-volume
          secret:
            secretName: sb-service
---
apiVersion: v1
kind: Service
metadata:
  name: sb-service
  labels:
    app: sb-service
spec:
  type: ClusterIP
  selector:
    app: sb-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080