apiVersion: v1
kind: Service
metadata:
  name: sb-client
  labels:
    app: sb-client
spec:
  type: LoadBalancer
  selector:
    app: sb-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
