apiVersion: v1
kind: Service
metadata:
  name: kube-helloworld-service
  labels:
    app: kube-helloworld
spec:
  type: LoadBalancer
  selector:
    app: kube-helloworld
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
