apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    lang: java
    type: config
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: tdoddareddy/kube-configserver
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: configserver-service
  labels:
    app: configserver
spec:
  type: ClusterIP
  selector:
    app: configserver
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
