apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-service-scs-deployment
  labels:
    lang: java
    type: config
    app: sb-service-scs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-service-scs
  template:
    metadata:
      labels:
        app: sb-service-scs
    spec:
      containers:
        - name: sb-service-scs
          image: tdoddareddy/kube-sbservice-scs:0.0.2-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes

---
apiVersion: v1
kind: Service
metadata:
  name: sb-service-scs
  labels:
    app: sb-service-scs
spec:
  type: ClusterIP
  selector:
    app: sb-service-scs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080